### DISCUSSION TITLE
v2.0.0b0

### DISCUSSION THREAD

**Discussion by mvdwetering** [mvdwetering/huesyncbox#55] [Announcements]
> **Note**
> This is a beta version, close to final, but could still use a few tweaks.

# Breaking Changes

> **Warning**
> All automations and dashboards using this integration will need to be updated!
> Make sure you have time for that when upgrading!

* Removed `media_player` entity
* Removed most custom services
* Minimum required Home Assistant Core version is now 2023.8.0

Read the changes section below and/or [README.md](https://github.com/mvdwetering/huesyncbox/blob/rebuild_integration/README.md) for more details.

# Changes

Before this version the functionality of the Philips Hue Play HDMI Sync Box was all exposed through one single mediaplayer entity. Several features of the media_player were abused to control things on the box. E.g. brightness was controlled by the volume slider. While this initially seemed like a good idea (easy controls on the dashboard and only one entity to implement) this turned out to be confusing and quite limiting in the long run. Next to that the way the integration was built did not allow for more entities so it was not possible to extend it. 

The 2.0 version is a complete rewrite to allow for multiple entities and modernize the integration in general. Having multiple entities should make it clear what the function of the entity is. And because they are standard Home Assistant entities like `switch`, `number`, `select` and `sensor` they are familiar to most users already.

With the rewrite several features are added that are nowadays standard for integrations, but did not exists back when this integration was created like select entity, reauth, diagnostics, easy enabling of logging and translations for everything. This rewrite also addresses most open issues and feature requests.

Since the integration is now using the latest and greatest Home Assistant features the minimum Home Assistant Core version is now 2023.8.0.

> **Note**
> No functionality is lost. It just moved to a different place.

> **Warning** 
> Because of the nature of the changes it means all automations and dashboards using this integration need to be updated.
> Home Assistant will _not_ load automations that use the removed services, so these have to be updated to use the new entities. In some cases Home Assistant generates repairs to help pinpoint the issue.

Below is a table with the old and new situation.

| New entity | Was implemented by |
|---|---|
| Power switch | Media player on/off |
| Light sync switch | Mediaplayer play/pause |
| Dolby Vision compatibility switch | _New feature_ |
| Intensity select | Mediaplayer sound modes |
| Mode select | Mediaplayer next/previous track |
| HDMI input select | Mediaplayer source |
| LED indicator select | _New feature_ |
| Brightness number | Mediaplayer volume or custom `set_brightness` service. Note that the range is now a percentage (0-100%) instead of 0 to 1 |
| HDMI1-4 connection status sensors | `hdmi1-4_status` attributes of mediaplayer |
| Bridge connection status sensor | `bridge_connection_state` attribute of mediaplayer  |
| Bridge ID sensor | `bridge_unique_id` attribute of mediaplayer  |
| IP address | _New feature_ |
| Wifi quality sensor | _New feature_ |

With the transition to the new entities most custom services that were offered became obsolete as native Home Assistant services of the entities can be used now. The following services have been removed. The table links to the documentation of the standard Home Assistant services that can be used instead.

| Old service name | Replaced by |
|---|---|
| set_brightness | Use services of the brightness [number entity](https://www.home-assistant.io/integrations/number/#services) |
| set_syncmode | Use services of the sync mode [select entity](https://www.home-assistant.io/integrations/select/#services) |
| set_intensity | Use services of the intensity [select entity](https://www.home-assistant.io/integrations/select/#services) |
| set_entertainment_area | Use services of the entertainment area [select entity](https://www.home-assistant.io/integrations/select/#services) |
| set_sync_state | Obsolete, use services on the specific entities instead |

And last the `yaml` configuration option has been removed. There was nothing that could be configured anyway, so the `huesyncbox:` entry can be safely removed.

**Full Changelog**: https://github.com/mvdwetering/huesyncbox/compare/v1.23.0...v2.0.0b0

**Comment by poudenes** [comment]
Hi There,

Great to see this big improvement of the code!!!

Add this beta to my test HA and check how new entities look like. So if I'm right than this will be the migration:
```
    - service: huesyncbox.set_sync_state
      data:
        sync: true
        mode: video
        intensity: moderate
        input: input1
        entertainment_area: TV room
        brightness: 0.7
      target:
        entity_id: media_player.sync_box
```
become this? :
```
     - service: switch.turn_on
       target:
         entity_id: switch.sync_box_power

     - service: switch.turn_on
       target:
         entity_id: switch.sync_box_light_sync

     - service: select.select_option
       data:
         option: "video"
       target:
         entity_id: select.sync_box_sync_mode sync_box_hdmi_input

     - service: select.select_option
       data:
         option: "moderate"
       target:
         entity_id: select.sync_box_intensity

     - service: select.select_option
       data:
         option: "TV room"
       target:
         entity_id: select.sync_box_entertainment_area

     - service: number.set_value
       data:
         value: "0.7"
       target:
         entity_id: numbers.sync_box_brightness

     - service: select.select_option
       data:
         option: "input1"
       target:
         entity_id: select.sync_box_hdmi_input
```

Ad if this will be the right way. Can you send the commands without delay in between?

**Reply by mvdwetering** [reply]
That is mostly right.

You can omit the turn on calls for `power` and `lightsync` because setting the mode will turn on the box and start lightsync. That is how the box reacts when sending the commands. 

There seems to be a copy-paste error in the entity_id for the syncmode as it has "sync_box_hdmi_input" at the end.

The brightness is now a percentage like in the Hue app, so 0.7 should be 70. The 0 to 1 range was to match the volume range in the media_player.

There is no need for delays.

Edit: you might want to check if this actually works. It could be that changing the entertainment area stops syncing. In that case change the area first. Same actually for switching input, that should probably also be done first.

**Reply by poudenes** [reply]
Thanks. Let me test this in upcoming days. I can change my HA simple from above horizon to below horizon and then all my automations will work :)... I'll let you know!

**Comment by poudenes** [comment]
Installed the latest version. Did some tests. Ordering seems important to let every service work correctly

Box intensity as last. Because when you change Sync Mode the intensity change also (configured in Sync Box Mobile app)
When you change intensity as last then you can control this. Otherwise it switch back when you change Sync mode.

And it seems that it is not needed to have a delay between them. 

When you just have always same settings when you watch movie/serie/tv/game then you just need the Light Sync option.

```
service: switch.turn_on
data: {}
target:
  entity_id: switch.sync_box_light_sync
```

Rest will stay as it is when you turn off the box.

Below the testing part I used:
```
    - service: select.select_option
      data:
        option: "game" # video, music, game
      target:
        entity_id: select.sync_box_sync_mode

    - service: select.select_option
      data:
        option: "TV room" # TV only, TV room
      target:
        entity_id: select.sync_box_entertainment_area

    - service: number.set_value
      data:
        value: "100" # 0 - 100
      target:
        entity_id: number.sync_box_brightness

    - service: select.select_option
      data:
        option: "HDMI 1" # HDMI 1, HDMI 2, HDMI 3, HDMI 4
      target:
        entity_id: select.sync_box_hdmi_input

    - service: select.select_option
      data:
        option: "high" # subtle, moderate, high, intense
      target:
        entity_id: select.sync_box_intensity
```
