### DISCUSSION TITLE
v2.0.0

### DISCUSSION THREAD

**Discussion by mvdwetering** [mvdwetering/huesyncbox#61] [Announcements]
# Breaking Changes

> **Warning**
> All automations and dashboards using this integration will need to be updated!
> Make sure you have time for that when upgrading!

* Removed `media_player` entity
* Removed/changed most custom services
* Minimum required Home Assistant Core version is now 2023.8.0
* Due to large amount of changes translations need to be re-done

Read the changes section below and/or the main [README.md](https://github.com/mvdwetering/huesyncbox) for more details.

# Changes

Before this version the functionality of the Philips Hue Play HDMI Sync Box was all exposed through one single mediaplayer entity. Several features of the media_player were abused to control things on the box. E.g. brightness was controlled by the volume slider. While this initially seemed like a good idea (easy controls on the dashboard and only one entity to implement) this turned out to be confusing and limiting in the long run. Next to that the way the integration was built did not allow for more entities so it was not possible to extend it. 

The 2.0.0 version is a complete rewrite to allow for multiple entities and modernize the integration in general. Having multiple entities should make it clear what the function of the entity is. And because they are standard Home Assistant entities like `switch`, `number`, `select` and `sensor` they are familiar to most users already.

With the rewrite several features are added that are nowadays standard for integrations, but did not exist back when this integration was created like reauth, diagnostics, select entities, easy enabling of logging and translations for everything. This rewrite also addresses most open issues and feature requests.

Since the integration is now using the latest and greatest Home Assistant features the minimum Home Assistant Core version is 2023.8.0.

Next to all the moving around of functionality, there are also a few new features.

The following entities were added:

* Dolby Vision compatibility switch
* LED indicator mode select
* IP address sensor
* Wifi quality sensor

# Migration info

## Notes

* On the upgrade a repair issue will be be created that indicates which automations are impacted to help find most automations that need updating (if any). This repair will stay available until February 2024.
* Home Assistant will not load automations that use the removed services, so these have to be updated to use the new entities. Look for automations with the "broken" robot icon.
* If you still have the `huesyncbox:` entry in `configuration.yaml`  it should be removed as it is not supported anymore.

## Entities

With the rewrite the existing `media_player` entity has been replaced with several new entities.
Below is a table with the old and new situation.

| Old |  New entity |
|---|---|
| Media player on/off | Power switch |
| Mediaplayer play/pause | Light sync switch |
| Mediaplayer sound modes | Intensity select |
| Mediaplayer next/previous track | Mode select |
| Mediaplayer source | HDMI input select |
| Mediaplayer volume | Brightness number. Note that the range is now a percentage (1-100%) to match the values in the Hue app. Volume was a range from 0 to 1 |
| `hdmi1-4_status` attributes of mediaplayer | HDMI1-4 connection status sensors |
| `bridge_unique_id` attribute of mediaplayer  | Bridge ID sensor |
| `bridge_connection_state` attribute of mediaplayer  | Bridge connection status sensor |

## Services

With the transition to the new entities most custom services that were offered became obsolete as native Home Assistant services of the entities can be used now. The table links to the documentation of the standard Home Assistant services that can be used instead.

| Old service name | Replaced by |
|---|---|
| set_brightness | Use services of the brightness [number entity](https://www.home-assistant.io/integrations/number/#services). Note that the range is now 1 to 100% to match the numbers in the Hue app. The range used to be 0 to 1 |
| set_syncmode | Use services of the sync mode [select entity](https://www.home-assistant.io/integrations/select/#services) |
| set_intensity | Use services of the intensity [select entity](https://www.home-assistant.io/integrations/select/#services) |
| set_entertainment_area | Use services of the entertainment area [select entity](https://www.home-assistant.io/integrations/select/#services) |
| set_sync_state | For toggle or cycle options use the services on the relevant entities.<br>The service can still be used to set multiple states at once for covenience so you don't have to worry about the order in which to set them.  |
| set_bridge | Not changed |

**Full Changelog**: https://github.com/mvdwetering/huesyncbox/compare/v1.23.0...v2.0.0

<hr /><em>This discussion was created from the release <a href='https://github.com/mvdwetering/huesyncbox/releases/tag/v2.0.0'>v2.0.0</a>.</em>

**Comment by IMNotMax** [comment]
Just to say thank you for your work.
Really appreciated !

**Reply by mvdwetering** [reply]
Thank you for the appreciation 👍

**Comment by cromelex** [comment]
I have been using the previous version sucessfuly for a good while, I have seen this but need to wait until I have a bit of time to upgrade all my automations.
In any case, thanks for the update, it is certainly a lot neater, from reading the description, than the previous implementation using the media player entities.

**Comment by jubjub03** [comment]
Hi, I'm fairly new to this HA stuff. I want to create buttons on my dashboard to select the source, intensity, etc. instead of a 'drop-down'. I was able to do this with the previous version. But not sure how to do it with the latest versions. Is anyone willing to share their code.

This is what I am essentially trying to do (the buttons are to change to that source (HDMI 1-4):
![image](https://github.com/mvdwetering/huesyncbox/assets/83611362/5cd93dec-1e09-4199-8af9-ec53b033be60)

I assume I need to call a service, but I am not sure I am doing this right. My approach may be all wrong. 

Any assistance would be greatly appreciated.

**Reply by mvdwetering** [reply]
Could you post how you did it before? I would expect using the selects would be similar.

I will post an example later when I am at my computer, doing on mobile is complicated.

**Reply by IMNotMax** [reply]
Hi, is this kind of thing you want to achieve 
![IMG_2829](https://github.com/mvdwetering/huesyncbox/assets/16235859/e73e370c-f2f0-4e56-a019-35dc53f995d7)
![IMG_2830](https://github.com/mvdwetering/huesyncbox/assets/16235859/f2956a70-09e6-4b57-8364-5d0889ed4ded)

**Reply by IMNotMax** [reply]
On mobile too but my config is straight forward
_Omg copy-paste add html %20 for each space_
> `cards:%0A%20%20%20%20%20%20-%20type%3A%20entities%0A%20%20%20%20%20%20%20%20entities%3A%0A%20%20%20%20%20%20%20%20%20%20-%20entity%3A%20number.sync_box_brightness%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20Brightness%0A%20%20%20%20%20%20%20%20%20%20-%20entity%3A%20select.sync_box_hdmi_input%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20HDMI%20Input%0A%20%20%20%20%20%20%20%20%20%20-%20entity%3A%20select.sync_box_intensity%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20Intensity%0A%20%20%20%20%20%20%20%20%20%20-%20entity%3A%20switch.sync_box_light_sync%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20Light%20Sync%0A%20%20%20%20%20%20%20%20%20%20-%20entity%3A%20switch.sync_box_power%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20Power%0A%20%20%20%20%20%20%20%20%20%20-%20entity%3A%20select.sync_box_sync_mode%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20Sync%20mode%0A%20%20%20%20%20%20%20%20title%3A%20Sync%20Box `

**Reply by mvdwetering** [reply]
Yeah that is why I don't try to do code on mobile :)
I actually meant the code for the Switch, Xbox etc... buttons that you have in the screenshot.

A single button would be like below.
Few things to note:
* The value for `option` is the _exact_ name of the input
* You need to replace the entityname `select.hobby_box_hdmi_input` with the one for your syncbox

```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: select.select_option
  target:
    entity_id: select.hobby_box_hdmi_input
  data:
    option: Nvidia Shield
name: Nvidia Shield
icon: mdi:shield
```

You can also configure it through the card configuration if you prefer. 
![image](https://github.com/mvdwetering/huesyncbox/assets/732514/b9075a2c-508b-47c3-9918-6e7860f7921f)

**Reply by jubjub03** [reply]
I am looking at the button option. The entity card works great, but I want to make it simpler for my family to use. I will try this tonight and let you know how I go. Thank you for the quick responses to providing help.

Unfortunately, I don't have backups of the old HA instance I had years ago so I don't have the previous config. I recently moved home and decided to revisit HA so I'm trying to get everything in that I currently have and will explore the huge world that there is.

Just with the above, what is defined as "Hobby box HDMI Input"? does this resemble the entity "select.sync_box_hdmi_input"?

**Reply by mvdwetering** [reply]
Yeah, one of my syncboxes is called Hobby Box so that shows in the entity name.

**Reply by jubjub03** [reply]
What am I missing here?

![image](https://github.com/mvdwetering/huesyncbox/assets/83611362/849d97c9-d7e0-49d7-9433-fc2e9c12e0b0)

Entity list for the sync box:

![image](https://github.com/mvdwetering/huesyncbox/assets/83611362/b36c44b0-3d55-4b25-8801-8ffe776d9a5f)

I don't get any options under "Area", "Device", "Entity" (no matches).

The default card it creates works fine.

![image](https://github.com/mvdwetering/huesyncbox/assets/83611362/293f0cfb-fff0-47e9-9b60-e60bd947420c)

As for the service "select: Select" I don't have this option. I only get "select: First", "select: Last" & "select: Next".

**Reply by mvdwetering** [reply]
The reason why you don't get results for area/device/entity is because you selected "Input Select: Select". It filters on areas/devices/entities that support the selected service. So if you would have selected "Light: Turn On" it area/devices/entities would only show lights.

I don't know why the "Select: Select" service would not show up as it is a standard service built into Home Assistant. Maybe refresh the browser?

**Comment by IMNotMax** [comment]
I've never tried this, but with a hue sync box and Select Input, I manage ta have some buttons for the 2 main inputs
![image](https://github.com/mvdwetering/huesyncbox/assets/16235859/06c12bac-eae7-44b2-9007-9f61bd2804a1)

```
  - type: horizontal-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_hdmi_input
          data:
            option: Apple TV
        name: AppleTV
        icon: mdi:apple
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_hdmi_input
          data:
            option: Xbox Séries X
        name: Xbox
        icon: mdi:microsoft-xbox
```

It's a great upgrade for the family (buttons are easier than lists)

(I @mvdwetering edited the post to fix the formatting of the text)

**Reply by IMNotMax** [reply]
You have to choose Sync Box HDMI Input to drive the list of inputs you have configured in the Hue or Hue Sync App

**Reply by jubjub03** [reply]
I finally got this to work, thank you. I don't know what happened but eventually the sevice 'select: select' finally appeared and I was able to select the correct entity.

**Reply by jubjub03** [reply]
Just in case someone wants some inspiration, although simple. Here is my buttons/dashboard to control my hue sync box.

![image](https://github.com/mvdwetering/huesyncbox/assets/83611362/3fcc0cc1-d8a8-4692-b21a-c2c667f403b7)

**Reply by IMNotMax** [reply]
Cool, could you share the yaml of this dashboard ?

**Reply by jubjub03** [reply]
Here it is:
_Note: I downloaded from HACS the "hass-hue-icons" and the "Custom brand icons" plug-in for the icons used below._

```
square: false
title: Hue Sync Box
type: grid
cards:
  - square: true
    type: grid
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        name: On/Off
        icon: ''
        hold_action:
          action: none
        entity: switch.sync_box_power
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.sync_box_light_sync
        name: Sync Lights
        icon: hue:lightstrip-tv
        hold_action:
          action: none
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_sync_mode
          data:
            option: video
        entity: select.sync_box_sync_mode
        name: Video
        icon: mdi:video
        hold_action:
          action: none
        show_state: false
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_sync_mode
          data:
            option: music
        entity: select.sync_box_sync_mode
        name: Music
        icon: mdi:music
        hold_action:
          action: none
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_sync_mode
          data:
            option: game
        entity: select.sync_box_sync_mode
        name: Game
        icon: hue:room-games
        hold_action:
          action: none
    columns: 5
  - type: entity
    entity: select.sync_box_sync_mode
    name: Synx Box Light Mode
    icon: hue:sync-box-alt
  - square: true
    type: grid
    cards:
      - show_name: false
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_hdmi_input
          data:
            option: Nintendo Switch
        icon: phu:nintendo-switch-logo
        name: Nintendo
        hold_action:
          action: none
        entity: select.sync_box_hdmi_input
      - show_name: false
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_hdmi_input
          data:
            option: Xbox
        icon: phu:xbox
        name: Xbox
        hold_action:
          action: none
        entity: select.sync_box_hdmi_input
      - show_name: false
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_hdmi_input
          data:
            option: Playstation
        icon: mdi:sony-playstation
        name: Playstation
        hold_action:
          action: none
        entity: select.sync_box_hdmi_input
      - show_name: false
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_hdmi_input
          data:
            option: Apple TV
        icon: phu:apple-tv-box
        name: Apple TV
        hold_action:
          action: none
        entity: select.sync_box_hdmi_input
    columns: 4
  - type: entity
    entity: select.sync_box_hdmi_input
    icon: hue:sync-box
  - square: true
    type: grid
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_intensity
          data:
            option: subtle
        icon: hue:sync-subtle
        name: Subtle
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_intensity
          data:
            option: moderate
        icon: hue:sync-moderate
        name: Moderate
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_intensity
          data:
            option: high
        icon: hue:sync-high
        name: High
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: select.select_option
          target:
            entity_id: select.sync_box_intensity
          data:
            option: intense
        icon: hue:sync-intense
        name: Intense
    columns: 4
  - type: entity
    entity: select.sync_box_intensity
    icon: hue:sync-intense
    name: Sync Box Light Intensity
    state_color: false
columns: 1
```
