### ISSUE TITLE
HomeKit shows 3 accessories

### ISSUE THREAD

**Issue by jakowenko** [mvdwetering/huesyncbox#19]
Hello,

Thank you for this awesome integration. I have it working within Home Assistant and exposed the media_player to HomeKit. I noticed within the Apple Home app there are three accessories that show up. I was curious what the difference was between the "Play-Pause" and "Play-Stop" actions. They both seem to do the same thing and when one is turned on/off the other also does the same.

![IMG_0104](https://user-images.githubusercontent.com/1081811/103314154-2237e800-49f0-11eb-8527-44c30b19c26c.jpg)

**Comment by jakowenko** [comment]
Closing as this has to do with the features of the media_player entity in HA and not the integration.

I was able to remove one of them by adding this to my configuration file.

```
homekit:
  entity_config:
    media_player.sync_box:
      feature_list:
        - feature: on_off
        - feature: play_stop
```
