### ISSUE TITLE
Error "Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02"

### ISSUE THREAD

**Issue by florie1706** [mvdwetering/huesyncbox#24]
**Describe the bug**
Somtimes when I use my automation (if hue syncbox is idle and tv is on then do hue syncbox sync_on) it does trigger but does not start the sync. In my log i have this

```
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:692
Integration: Mediaplayer (documentation, issues)
First occurred: 16. September 2021, 06:51:50 (167 occurrences)
Last logged: 16:24:47

Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
```

**Expected behavior**
Send a sucessfull sync_on to the box

**Environment**
Official docker image

- Home Assistant Core version: 2021.9.7
- Home Assistant operating environment (OS/Container/Supervised/Core): Docker
- Huesyncbox integration version: 1.14.0

**Comment by mvdwetering** [comment]
The `Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02` lines are kind of expected to happen occasionally. Typically the box returns an answer really fast (couple of milliseconds), but sometimes it seems busy and can take a bit longer. I get a couple of these a day on my setup. 

I could make the poll interval longer again (it was lowered from 10 to 2 in the last update), but it would take longer for the integration to get in sync with the status of the box, which is a problem when building automations around it.

Seeing that line would only mean that the status of the integration will lag behind with ~2 seconds. So as long is it is not occurring around the time that the status of the box changes and your automation triggers it should not be an issue.

That being said, could you post your automation (the yaml) so I can try to reproduce it.

I would expect request errors to the box to be logged by HA since it is an Exception, but maybe that is not (always?) the case, I would need to examine that in more detail. 
It would really help if you could enable the aiohuesyncbox logging by adding or extending the section below in your `configuration.yaml`. And save it when the issue occurs. However it is really spammy as it logs each request to the box (which means every 2 seconds) and it prints quite a lot of data. But it is the only way to really see what is going on on the communication level.
```
logger:
  default: info
  logs:
    aiohuesyncbox: debug
```

**Comment by florie1706** [comment]
Hi, thanks for your answer. I can do that, when I am back home. But I think the poll is correct every time. The automation triggers but the part which is not running is the action part of the automation. This is not working like every third time when using my Apple TV.

The automation looks like this:
```
- id: '1631614592237'
  alias: Hue Sync Box aktivieren
  description: ''
  trigger:
  - platform: device
    device_id: 785ee3ab566d77d792ae95122733ab3d
    domain: media_player
    entity_id: media_player.wozi
    type: idle
  - platform: device
    device_id: 785ee3ab566d77d792ae95122733ab3d
    domain: media_player
    entity_id: media_player.wozi
    type: idle
    for:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: b3830cd7396acef86861954a86840eb9
    entity_id: remote.wohnzimmer
    domain: remote
  action:
  - device_id: 785ee3ab566d77d792ae95122733ab3d
    domain: huesyncbox
    entity_id: media_player.wozi
    type: sync_on
  mode: restart
  max: 10
```

I put a second trigger with a delay of 10 seconds as a workaround (to send the action a second time after 10 seconds if the first send did not went thru), that seems to work yesterday.

As I said before I think the action does not arrive at the sync box every time for me.

**Comment by SkywiperSolutions** [comment]
Any news on a permanent fix for this?
Thanks!

**Comment by sparsons99** [comment]
I get this issue a lot, It can be approximately every 30 seconds for periods, and then stops doing it for a while, then comes back again! It doesn't stop it working but it makes my log file somewhat busy!

Completely understand that it could very well be down to local network conditions (I have a lot of equipment on my network!) but would it be possible to add an option in a future version to change the poll interval if we want to? That way we can adjust it to something that works for us. I have no issue waiting 5-10 seconds for my lights to start syncing or change modes, but others may want it quicker. An option for the user to change this might be a way to solve this.

Thanks for the great component though, I was sending rest commands manually before and it was very hit and miss, this works so much better!!

**Comment by mvdwetering** [comment]
Ow, sorry for the late reply. I somehow missed the 20 sept response.

@sparsons99 Since I am using the standard `SCAN_INTERVAL` thing in HA you might be able to override it `configuration.yaml` as documented here https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval
Other option could be the "Disable polling" option introduced in HA 2021.6 (https://www.home-assistant.io/blog/2021/06/02/release-20216/#disable-polling-updates-on-any-integration) and manage your own update frequency.

I am planning to do some work on the integration during the upcoming holidays and will take a look at this.

However it would really help to get some logging of the traffic to the syncbox so if one of you could temporarily enable the logging by adding the section below to `configuration.yaml` and reproduce the issue that would help a lot. It helps me to see if the box returns an error, there is a timeout or maybe something else.

```
logger:
  default: info
  logs:
    huesyncbox: debug
    aiohuesyncbox: debug
```
