### ISSUE TITLE
problem publishing switches on Homekit bridge

### ISSUE THREAD

**Issue by pilot1981** [mvdwetering/huesyncbox#68]
Hi,
I removed media player from my Homekit bridge integration.

this is my old configuration:
```
 - name : HASSIO Bridge Sync Box
    port: 21065
    mode: accessory
    filter:
      include_entities:
        - media_player.sync_box_2
    entity_config:
      media_player.sync_box_2:
        feature_list:
          - feature: on_off
          - feature: play_stop
```

I changed it in this new configuration:
```
  - name : HASSIO Bridge Sync Box
    port: 21065
    mode: accessory
    filter:
      include_entities:
        - switch.sync_box_power
        - switch.sync_box_light_sync
```

but I see only switch.sync_box_power in Homekit...
why I can't see also switch.sync_box_light_sync?

EDIT: Fix yaml formatting
